version: '{build}'

environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.16.0

install:
  - ps: choco install ant
  - ps: $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
  - java -version
  - ant -version

build_script:
  - cmd: SET PATH=C:\Program Files (x86)\WiX Toolset v3.10\bin;C:\Program Files (x86)\Inno Setup 5;%PATH%
  - cd MAVGCL
  - ant deploy_windows

artifacts:
  - path: MAVGCL/dist/deploy/bundles/MAVGAnalysis*.exe
    name: mavgclinstaller

cache:
  - C:\Users\appveyor\.m2

deploy:
  - provider: GitHub
    auth_token:
      secure: Hq5VDnfPj9yDRim502Eyhn7rFSgjfo3TiRs2xM+qP/wm/Wav6q/XeVNIGEEdXbtN
    artifact: mavgclinstaller
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
